Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "https://reviewhub.ngrok.com"
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://review-hub.herokuapp.com"
  <<: *defaults
